### ISSUE TITLE
关于代码跑recall指标

### ISSUE THREAD

**Issue by zxs9494la** [CCIIPLab/MCCLK#10]
作者您好，在复现您发布的代码时，train_res按照您的注释，我变成添加 ["Recall@5", "Recall@10", "Recall@20", "Recall@50", "Recall@100"], 但是实验跑出来 recall却是nan值，中间调试了很久也不行，想向您询问一下细节。

**Comment by ding523** [comment]
非常感谢关注，这个相关问题似乎之前邮件回复过您，请注意查收！
（另，您可以再仔细看看代码部分，需要进行topk_eval后再add对应的topk结果的

**Comment by Lilyzhangyanlin** [comment]
你好，我也想复现一下这个recall指标。可以在这里讲一下邮件中具体的细节吗？谢谢！

**Comment by hh-hua** [comment]
> 作者您好，在复现您发布的代码时，train_res按照您的注释，我变成添加 ["Recall@5", "Recall@10", "Recall@20", "Recall@50", "Recall@100"], 但是实验跑出来 recall却是nan值，中间调试了很久也不行，想向您询问一下细节。

首先在测试集训练的时候加入 recall = topk_eval(model, train_cf, test_cf)，然后按照您说的将那些注释取消掉
