### ISSUE TITLE
数据集读入问题

### ISSUE THREAD

**Issue by wangxin211** [CCIIPLab/MCCLK#11]
请问数据集在读入时， 在ratings_final文件中权值为0的交互为何也被读入训练集中？

**Comment by ding523** [comment]
非常感谢关注，这是pair-wise和point-wise loss对于训练集数据读入的不同需求。
实际上目前kgrs相关工作中，有用bce和bpr不同loss的工作（可见kgcn与kgin，分别使用bce和bpr），这个发布的版本里采用的是bce_loss，所以读入的是包含label为和0两种的交互；如果用bpr的话，则可以只读入label为1的数据，neg通过负采样得到。

**Comment by ieqiangguo** [comment]
作者您好！请问ratings_final.txt中label为0的U-I交互的数据是怎么生成的？谢谢。
