### ISSUE TITLE
超参数设置问题

### ISSUE THREAD

**Issue by java-jay** [CCIIPLab/MCCLK#12]
作者你好！我想按您论文里的超参数方法进行设置，但我在代码里不知道这些超参数是在哪里

**Comment by ding523** [comment]
您好！首先非常感谢关注！
其次大部分参数是在parser.py中，有少部分参数以self.xx的形式放在MCCLK.py中，之前上传匆忙，并未将所有参数均add到parser，烦请见谅，后面会整理一个合适的版本更新的！
