### ISSUE TITLE
 想请问一下为什么论文里写的是BprLoss而代码写的BceLoss

### ISSUE THREAD

**Issue by bugdog-zzy** [CCIIPLab/MCCLK#19]
想问一下作者就是论文里用的是BprLoss而代码写的BceLoss，然后也没有看到有关负样本采样的代码，可以指出原因吗

**Comment by ding523** [comment]
感谢关注，两种loss其实都有实验，性能相差不大，只是对比的baseline大多用的bceloss，故而上传的这一版代码中味bceloss
所采用的三个数据集的格式中若要采用bprloss需要负采样，可使用普通的随机负采样方案即可，示例如下：
def negative_sampling(user_item, train_user_set):
        neg_items = []
        for user, _ in user_item.cpu().numpy():
            user = int(user)
            while True:
                neg_item = np.random.randint(low=0, high=n_items, size=1)[0]
                if neg_item not in train_user_set[user]:
                    break
            neg_items.append(neg_item)
        return neg_items
