### ISSUE TITLE
关于超参数的一些疑问

### ISSUE THREAD

**Issue by DuTim** [CCIIPLab/MCCLK#3]
你好,在复现模型效果时,发现效果有不小的差距. 
 在论文中使用 alpha, beta 来对损失的权重进行均衡,但是在代码中好像没有体现这部分内容,是我没有正确理解吗,
![image](https://user-images.githubusercontent.com/50939742/172640785-92388b57-d92e-4143-8865-ef226f6d9fc7.png)

**Comment by CCIIPLab** [comment]
感谢关注。
首先两个参数并未在parser.py中add，而是直接在model中以self.alpha或beta体现的。
有关alpha参数，此上传的版本确实在这里是有遗漏该参数，但您可以查看上面几行注释的代码，是有alpha参数的，可直接进行替换；此外您可以手动设置该超参。
有关beta参数，该上传版本的create_bpr_loss函数的return处有对应参数数值（bce_loss+emb_loss+0.001*loss_contrast）。
