### ISSUE TITLE
About the Movielens-1M dataset

### ISSUE THREAD

**Issue by tuabo** [CCIIPLab/MCCLK#4]
Hi, thank you for your work. The number of triples in the MovieLens-1M dataset you uploaded is only 20782. The number of triplets for MovieLens-1M preprocessed by RippleNet is 1,241,995, but in your paper it is 1,241,996. Can you upload the triples in the MovieLens-1M dataset? Thanks.

**Comment by brokenvvorld** [comment]
I have the same problem.
