### ISSUE TITLE
模型实现与论文描述

### ISSUE THREAD

**Issue by Tuo97** [CCIIPLab/MCCLK#5]
您发布的这一版本代码与论文中的许多描述不一致，尤其是在全局和局部特征对比部分。我发现您在模型中的许多地方进行了注释，请问如何与论文方法完全对应？

**Comment by ding523** [comment]
感谢关注。
有关注释问题：部分注释为ablation的代码，如有带来困惑可以忽略。（上传版本为某个ablation的variant情况，各种variant均在code中）
描述一致问题：由于上传版本仓促原因，contrast可能部分被ablated了，这个我会稍后抽时间更正！感谢指出。

另外，我们的工作也被集成到了人大的Recbole框架中( https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/knowledge_aware_recommender/mcclk.py )，您着急了解的话也可以参考一下那边的实现，部分实现的问题我们也与recbole的人员交流过（包括semantic view与path view相关问题，局部与全局两级对比的问题），可能会包含您的疑惑。

**Comment by Tuo97** [comment]
好的，非常感谢
