### ISSUE TITLE
Book数据集运行配置？

### ISSUE THREAD

**Issue by chuxin01** [CCIIPLab/MCCLK#6]
您好，请问MCCLK在Book数据集运行需要多少g的显存？

**Comment by ding523** [comment]
感谢关注！映像中Book数据集显存需求在12G以内，Movie可能略超过12G。

**Comment by chuxin01** [comment]
您好，感谢回复。另外有个问题，在看您的代码的过程中发现MCCLK是在80%训练集和20%测试集的基础上做的实验，并未使用验证集。请问您有做带验证集的实验吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6)





 
感谢关注！映像中Book数据集显存需求在12G以内，Movie可能略超过12G。

**Comment by ding523** [comment]
这里是follow的KGIN的做法划分的（8:2），映像中我两种划分都写在dataloader里过，你可以找找，如果没有的话自行按照（6:2:2）划分即可。
（也可参考我们的另一个KGIC工作里的处理，应该follow的ripplenet进行的6:2:2划分）

**Comment by chuxin01** [comment]
好的，感谢回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月14日(星期一) 晚上9:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6)





 
这里是follow的KGIN的做法划分的（8:2），映像中我两种划分都写在dataloader里过，你可以找找，如果没有的话自行按照（6:2:2）划分即可。
 （也可参考我们的另一个KGIC工作里的处理，应该follow的ripplenet进行的6:2:2划分）

**Comment by chuxin01** [comment]
您好，您在2022年关于知识感知推荐的两个工作：KGIC、MCCLK十分优秀，我们想要对比你们这俩个模型，但是他们的数据集划分分别为8:2和6:2:2，为此我们将其统一为6:2:2,在统一后，KGIC依旧十分优秀，但是MCCLK在music和book数据集的效果下降明显，注意到MCCLK的alpha和beta在您github仓库的代码与论文描述不一致，我们详细根据论文进行比对，在设置正确完毕后，依旧表现并不乐观，最终music和book数据集的AUC和F1结果分别为0.851、0.775以及0.731、0.659。
为此我们想请教一下是否L2正则化权重和学习率设置不是最佳，我们对L2正则化和学习率lr的设定按照MCCLK在github上传的结果，分别为：1e-5、3e-3。
另外，如果您之前有MCCLK6:2:2数据集设定的结果，能否分享参考一下，十分感谢！
期待您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6)





 
这里是follow的KGIN的做法划分的（8:2），映像中我两种划分都写在dataloader里过，你可以找找，如果没有的话自行按照（6:2:2）划分即可。
 （也可参考我们的另一个KGIC工作里的处理，应该follow的ripplenet进行的6:2:2划分）

**Comment by chuxin01** [comment]
您好，您在2022年关于知识感知推荐的两个工作：KGIC、MCCLK十分优秀，我们想要对比你们这俩个模型，但是他们的数据集划分分别为8:2和6:2:2，为此我们将其统一为6:2:2,在统一后，KGIC依旧十分优秀，但是MCCLK在music和book数据集的效果下降明显，注意到MCCLK的alpha和beta在您github仓库的代码与论文描述不一致，我们详细根据论文进行比对，在设置正确完毕后，依旧表现并不乐观，最终music和book数据集的AUC和F1结果分别为0.851、0.775以及0.731、0.659。
为此我们想请教一下是否L2正则化权重和学习率设置不是最佳，我们对L2正则化和学习率lr的设定按照MCCLK在github上传的结果，分别为：1e-5、3e-3。
另外，如果您之前有MCCLK6:2:2数据集设定的结果，能否分享参考一下，十分感谢！
期待您的回复！
另外，附上我们在6：2：2的数据集划分下music以及book数据集的CTR预估实验结果。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6)





 
这里是follow的KGIN的做法划分的（8:2），映像中我两种划分都写在dataloader里过，你可以找找，如果没有的话自行按照（6:2:2）划分即可。
 （也可参考我们的另一个KGIC工作里的处理，应该follow的ripplenet进行的6:2:2划分）

**Comment by ding523** [comment]
感谢关注！
&nbsp; &nbsp; &nbsp; 关于在6-2-2设置下下降较大的问题，实际上训练集标签减少对于模型效果有影响应该是属于正常的，只是之前我们并未进行对应的研究，所以合适的参数值我们这边也难以给出，后续有时间我也会仔细找找具体的影响部分在哪（现在忙于找实习，确实不太能抽空做相关更新，非常抱歉）。
&nbsp; &nbsp; &nbsp; 也非常佩服感谢您的耐心和严谨！建议您那边可以先自行调参，取一个时间精力范围内能取得的最佳效果作为baseline结果即可。
&nbsp; &nbsp; &nbsp; 此外，映像中l2和lr的影响似乎并没有非常大。
&nbsp; &nbsp; &nbsp; 同时，model部分我上传的版本是某个ablation实验的版本，可以把注释的几行恢复，应该效果会有变化，这个部分一直忘了调整了，不知道您那边之前有没有注意到。
   同时，mcclk也被rucbole复现过，也可以看看他们的复现代码中的参数或者设置 https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/knowledge_aware_recommender/mcclk.py).





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6)





 您好，您在2022年关于知识感知推荐的两个工作：KGIC、MCCLK十分优秀，我们想要对比你们这俩个模型，但是他们的数据集划分分别为8:2和6:2:2，为此我们将其统一为6:2:2,在统一后，KGIC依旧十分优秀，但是MCCLK在music和book数据集的效果下降明显，注意到MCCLK的alpha和beta在您github仓库的代码与论文描述不一致，我们详细根据论文进行比对，在设置正确完毕后，依旧表现并不乐观，最终music和book数据集的AUC和F1结果分别为0.851、0.775以及0.731、0.659。 
 为此我们想请教一下是否L2正则化权重和学习率设置不是最佳，我们对L2正则化和学习率lr的设定按照MCCLK在github上传的结果，分别为：1e-5、3e-3。 
 另外，如果您之前有MCCLK6:2:2数据集设定的结果，能否分享参考一下，十分感谢！ 
 期待您的回复！ 
 另外，附上我们在6：2：2的数据集划分下music以及book数据集的CTR预估实验结果。 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年11月14日(星期一) 晚上9:08 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6) 
 
 
 
 
 
   
 这里是follow的KGIN的做法划分的（8:2），映像中我两种划分都写在dataloader里过，你可以找找，如果没有的话自行按照（6:2:2）划分即可。 
  （也可参考我们的另一个KGIC工作里的处理，应该follow的ripplenet进行的6:2:2划分）

**Comment by chuxin01** [comment]
非常感谢您能在百忙之中抽空回复邮件！您在2022年关于知识感知推荐的两篇文章都非常的优秀，给我们很多启发。那我先进行自行调参，实验。在这里祝您实习顺利，工作顺心！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6)





 感谢关注！ 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; 关于在6-2-2设置下下降较大的问题，实际上训练集标签减少对于模型效果有影响应该是属于正常的，只是之前我们并未进行对应的研究，所以合适的参数值我们这边也难以给出，后续有时间我也会仔细找找具体的影响部分在哪（现在忙于找实习，确实不太能抽空做相关更新，非常抱歉）。 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; 也非常佩服感谢您的耐心和严谨！建议您那边可以先自行调参，取一个时间精力范围内能取得的最佳效果作为baseline结果即可。 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; 此外，映像中l2和lr的影响似乎并没有非常大。 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; 同时，model部分我上传的版本是某个ablation实验的版本，可以把注释的几行恢复，应该效果会有变化，这个部分一直忘了调整了，不知道您那边之前有没有注意到。 
    同时，mcclk也被rucbole复现过，也可以看看他们的复现代码中的参数或者设置 https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/knowledge_aware_recommender/mcclk.py). 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月6日(星期四) 晚上6:22 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6) 
 
 
 
 
 
  您好，您在2022年关于知识感知推荐的两个工作：KGIC、MCCLK十分优秀，我们想要对比你们这俩个模型，但是他们的数据集划分分别为8:2和6:2:2，为此我们将其统一为6:2:2,在统一后，KGIC依旧十分优秀，但是MCCLK在music和book数据集的效果下降明显，注意到MCCLK的alpha和beta在您github仓库的代码与论文描述不一致，我们详细根据论文进行比对，在设置正确完毕后，依旧表现并不乐观，最终music和book数据集的AUC和F1结果分别为0.851、0.775以及0.731、0.659。  
  为此我们想请教一下是否L2正则化权重和学习率设置不是最佳，我们对L2正则化和学习率lr的设定按照MCCLK在github上传的结果，分别为：1e-5、3e-3。  
  另外，如果您之前有MCCLK6:2:2数据集设定的结果，能否分享参考一下，十分感谢！  
  期待您的回复！  
  另外，附上我们在6：2：2的数据集划分下music以及book数据集的CTR预估实验结果。  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人:                                                                                                                        "CCIIPLab/MCCLK"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年11月14日(星期一) 晚上9:08  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [CCIIPLab/MCCLK] Book数据集运行配置？ (Issue #6)  
   
   
   
   
   
     
  这里是follow的KGIN的做法划分的（8:2），映像中我两种划分都写在dataloader里过，你可以找找，如果没有的话自行按照（6:2:2）划分即可。  
   （也可参考我们的另一个KGIC工作里的处理，应该follow的ripplenet进行的6:2:2划分）

**Comment by UPCRS** [comment]
> 非常感谢您能在百抽空回复邮件！您在2022年关于获取知识推荐的两篇忙碌文章都非常的优秀，给我们启发。那我先进行一下亲自调参，实验。在这里祝您实习顺利，工作顺利顺心！
> [……](#)
> ------------------ 原始邮件 -------------------- 发件人: "CCIIPLab/MCCLK “* **@***.***>;发送时间： 2023年4月10日（周一）下午3:24 ***@***.***>; ***@***.* *****@***.***>;主题: 回复: [CCIIPLab/MCCLK] 图书数据集运行配置？（问题#6）感谢关注！   关于在6-2-2设置下增量增加的问题，实际上训练集标签减少对于模型效果有影响应该是正常的，只是在我们感应之前进行对应的研究，所以合适的参数值属于我们心理学也难以给出，后续有时间我再仔细寻找具体的影响部分在哪（现在忙着找实习，确实不太能抽空做相关更新，非常遗憾）。   也非常佩服您的耐心和严谨！建议可以先自行调参，取一个最佳时间精力范围内能取得的效果作为核心结果即可。   另外，比如说l2和lr的影响似乎并没有非常大。   同时，模型部分我上传的版本是某个消融实验的版本，可以把注释的几行恢复，效果应该会有变化，这部分一直忘记调整了，不知道你之前有没有注意到。，mcclk也被rucbole复现过，也可以看查看他们的详细代码中的参数或者设置https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/knowledge_aware_recommender/mcclk.py）。
> ------------------ 原始邮件-------------------- 发件人: “CCIIPLab/MCCLK”* **@***.***>;时间：2023年4月6日(星期四)晚上6:22 ***@***.***>; **@***.******@***.***>;主题: 回复: [CCIIPLab/MCCLK] 图书数据集运行配置？（[第6](https://github.com/CCIIPLab/MCCLK/issues/6)期）您好，您在2022年关于知识采集推荐的两个作品：KGIC、MCCLK十分优秀，我们想要对比你们这两个模型，但是他们的数据集划分分别为8:2和6:2:2，因此我们将其统一为6 :2:2，但是在统一后，KGIC依然十分优秀，MCCLK在音乐和图书数据集的效果下降明显，注意MCCLK的alpha和beta在您github仓库的代码与论文描述不一致，我们根据论文进行比对，在设置详细之后，仍然表现乐观并不，最终音乐和书籍数据集的AUC和F1结果分别为0.851、0.775以及0.731、0.659。因此我们想请教此时L2正则化权重和学习率设置不是最好的我们，对L2正则化权重和学习率lr的设置按照MCCLK在github上传的结果，分别为：1e-5、3e-3。另外，如果您之前有MCCLK6:2:2数据集设置的结果，能否分享参考，十分感谢！期待您的回复！另外，附上我们在6：2：2的数据集划分下音乐以及书籍数据集的点击率实验结果。
> ------------------ 原始邮件 ------------------ 发件人: "CCIIPLab/MCCLK" *** @***.***>;发送时间：2022年11月14日（周一）晚上9:08 ***@***.***>; ***@***.******@***.***>;主题: 回复: [CCIIPLab/MCCLK] BookDataset运行配置？ (Issue #6 )这里按照KGIN划分的做法是（8:2），比如说我的划分都写在dataloader里过，你可以找找，如果没有的话按照（6:2:2）划分即可。（也参考我们的另一个KGIC 工作里的处理，应该遵循 Ripplenet 进行的 6:2:2 划分） — 直接回复此电子邮件，在 GitHub 上查看它，或取消订阅。您收到此消息是因为您创作了该主题。消息ID ：***@***.***> — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您发表了评论。消息 ID：***@** *.***> — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：***@***.***>

您好，请问您这篇论文复现的结果怎么样呀，可以交流下吗，我跑的结果比作者的低几个点，谢谢
