### ISSUE TITLE
关于环境配置问题

### ISSUE THREAD

**Issue by ZQSong1997** [CCIIPLab/MCCLK#7]
您好，pt1.5.0好像不支持torch_sparse==0.6.10，要pytorch1.8以上才支持。我按照文件描述配置环境后发生了如下报错，原因好像就出在torch_sparse上。请问您是怎么解决的呢？
![image](https://user-images.githubusercontent.com/46641090/205475873-3126d575-63d5-41c4-a32a-20ea6090b5ba.png)

**Comment by ding523** [comment]
您好，感谢关注。
首先torch_sparse==0.6.10是必须的，映像中低版本不支持稀疏张量和稀疏张量间的乘法；
如果torrch==1.5.0冲突的话可以自行安装更高版本的torch，1.7.1似乎就足够了，torch兼容性还是非常优秀的，不用担心单独选用更高版本torch会有其他的问题。

**Comment by ZQSong1997** [comment]
> 您好，感谢关注。 首先torch_sparse==0.6.10是必须的，映像中低版本不支持稀疏张量和稀疏张量间的乘法； 如果torrch==1.5.0冲突的话可以自行安装更高版本的torch，1.7.1似乎就足够了，torch兼容性还是非常优秀的，不用担心单独选用更高版本torch会有其他的问题。

**Comment by ZQSong1997** [comment]
> 您好，感谢关注。 首先torch_sparse==0.6.10是必须的，映像中低版本不支持稀疏张量和稀疏张量间的乘法； 如果torrch==1.5.0冲突的话可以自行安装更高版本的torch，1.7.1似乎就足够了，torch兼容性还是非常优秀的，不用担心单独选用更高版本torch会有其他的问题。

好的，非常感谢您的帮助！
