### ISSUE TITLE
There is a discrepancy between the model code and the paper？

### ISSUE THREAD

**Issue by zhiweihu1103** [CCIIPLab/MCCLK#8]
Hi, folk, nice job.
Taking the music dataset as an example, when I checked the code, I found that there are some differences between the model part and the description of the paper, as follows:
In the following line, I see item_emb = self.all_embed[self.n_users:, :]:
https://github.com/CCIIPLab/MCCLK/blob/4b0d2843b73adbe816a7a5bb1788b4f4bcd777f4/modules/MCCLK.py#L256

But the number of items is 3846, and the number of entities is 9366. Why is the embedding of the entity assigned to the embedding of the item? In the later part of the code, the embedding of item and entity is also confusing back and forth. Can you explain it?

**Comment by ding523** [comment]
Hi, thanks greatly for attention. Such an implementation follows KGIN, which unifys the item and entity toghther, and you could find the details in dataloader or refer to that work (https://github.com/huangtinglin/Knowledge_Graph_based_Intent_Network).
